
version: "3"
services:
  db:
    image: mysql:latest
    restart: always
    environment:
        MYSQL_DATABASE: webapp
        MYSQL_PASSWORD: secret
        MYSQL_ROOT_PASSWORD: secret
        MYSQL_USERNAME: yuta
    ports:
        - "13306:3306"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d
      - ./mysql/data:/var/lib/mysql
    stdin_open: true
    networks:
      - br0
#my.cnf ignored出たらchmod 644 /etc/mysql/conf.d/my.cnf
  php:
    build: ./php
    volumes:
      - ./nginx/html:/usr/share/nginx/html
      - ./php/php.ini:/usr/local/etc/php/conf.d/php.ini
    depends_on: ["db"]

  nginx:
    # image: nginx:latest
    build: ./web
    # container_name: docker-compose-mailhog-nginx
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/html:/var/www/html
    restart: always
    ports: ["8080:80"]
    depends_on: ["php"]
    networks:
      - br0

  
  mailhog:
    container_name: docker-compose-mailhog-mailhog
    image: 'mailhog/mailhog:latest'
    ports:
      - '1025:1025'
      - '8025:8025'
    networks:
      - br0
 

networks:
  br0:
    driver: bridge