
version: "3"
services:
  db:
    image: mysql:latest
    restart: always
    environment:
        MYSQL_DATABASE: webapp
        MYSQL_PASSWORD: secret
        MYSQL_ROOT_PASSWORD: secret
    ports:
        - "4306:3306"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      # - ./sql/mysql:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
      # - ./sql/mysql/sql/:/docker-entrypoint-initdb.d/
    stdin_open: true

  php:
    build: ./php
    volumes:
      - ./nginx/html:/usr/share/nginx/html
      - ./php/php.ini:/usr/local/etc/php/conf.d/php.ini
    depends_on: ["db"]

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/html:/usr/share/nginx/html
    restart: always
    ports: ["8081:80"]
    depends_on: ["php"]